const LOGIN_ATTEMPTS = 3;
const UNITLL_UNBLOCK_DURATION = 5; // IN MINUTES
const DURATION_TO_FAIL_ATTEMPTS = 5; // minutes
const TIME_BEFORE_NEXT_PIN_REQUEST = 3; // minutes
const TIME_BEFORE_PIN_TRIAL_ELAPSE = 3; // minutes
const MAX_PIN_TRIAL_ATTEMPTS = 5;

export default {
  LOGIN_ATTEMPTS,
  UNITLL_UNBLOCK_DURATION,
  DURATION_TO_FAIL_ATTEMPTS,
  TIME_BEFORE_NEXT_PIN_REQUEST,
  TIME_BEFORE_PIN_TRIAL_ELAPSE,
  MAX_PIN_TRIAL_ATTEMPTS,
};
