const QUERY_BADGE_SIZE = 10;
const MAXIMUM_DEBT_BEFORE_ACCOUNT_DISABLE = 100;
const PLATFORM_PERCENTAGE_CHARGE_PER_TRIP = 10;
export default {
  MAXIMUM_DEBT_BEFORE_ACCOUNT_DISABLE,
  QUERY_BADGE_SIZE,
  PLATFORM_PERCENTAGE_CHARGE_PER_TRIP,
};
